version: '3.1'

services:

  db:
    image: ambiverse/nlu-db-cassandra
    restart: always
    environment:
      DATABASE_NAME: aida_20180120_cs_de_en_es_ru_zh_v18

  nlu:
    image: ambiverse/ambiverse-nlu
    restart: always
    depends_on:
      - db
    ports:
      - 8080:8080
    environment:
      AIDA_CONF: aida_20180120_cs_de_en_es_ru_zh_v18_cass